package za.co.impilodrilling.register
import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.pdf.PdfDocument;import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.activity.OnBackPressedCallback;import androidx.appcompat.app.AppCompatActivity;import androidx.core.content.FileProvider;import org.json.JSONArray;import java.io.File;import java.text.SimpleDateFormat;import java.util.*
class MainActivity:AppCompatActivity(){
 private val prefs by lazy{getSharedPreferences("impilo_register",MODE_PRIVATE)};private val staff=mutableListOf<String>();private lateinit var content:FrameLayout;private var selectedDate=today();private var selectedStaff:String?=null;private var noteEdit:EditText?=null;private var originalNote="";private var screen="home";private val green=Color.rgb(11,95,70);private val dark=Color.rgb(28,36,33);private val muted=Color.rgb(95,105,101)
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_main);content=findViewById(R.id.content);loadStaff();selectedStaff=staff.firstOrNull();findViewById<Button>(R.id.navHome).setOnClickListener{guard{showHome()}};findViewById<Button>(R.id.navRegister).setOnClickListener{guard{showRegister()}};findViewById<Button>(R.id.navStaff).setOnClickListener{guard{showStaff()}};onBackPressedDispatcher.addCallback(this,object:OnBackPressedCallback(true){override fun handleOnBackPressed(){if(dirty())unsaved{finish()}else if(screen!="home")showHome() else finish()}});showHome()}
 private fun base(title:String):LinearLayout{val sc=ScrollView(this);val root=LinearLayout(this);root.orientation=LinearLayout.VERTICAL;root.setPadding(dp(20),dp(18),dp(20),dp(28));sc.addView(root);content.removeAllViews();content.addView(sc);root.addView(tv("IMPILO DRILLING",13,true,green));root.addView(tv(title,30,true,dark).apply{setPadding(0,0,0,dp(16))});return root}
 private fun showHome(){screen="home";noteEdit=null;val r=base("Staff Register");val h=Calendar.getInstance().get(Calendar.HOUR_OF_DAY);r.addView(tv(if(h<12)"Good Morning" else if(h<17)"Good Afternoon" else "Good Evening",22,true,dark));r.addView(tv(SimpleDateFormat("EEEE, d MMMM yyyy",Locale.getDefault()).format(Date()),15,false,muted).apply{setPadding(0,0,0,dp(14))});val total=staff.size;val td=today();val done=staff.count{!prefs.getString(key(it,td),"").isNullOrBlank()};card(r,"STAFF MEMBERS",total.toString(),"Manage your team"){showStaff()};card(r,"TODAY'S RECORDS",done.toString()+" / "+total,done.toString()+" employees have records today"){selectedDate=td;showRegister()};card(r,"MISSING TODAY",(total-done).toString(),"No daily note saved yet"){val m=staff.firstOrNull{prefs.getString(key(it,td),"").isNullOrBlank()};if(m!=null)selectedStaff=m;selectedDate=td;showRegister()};card(r,"DAILY REGISTER","OPEN REGISTER","Quickly record today's notes"){selectedDate=td;showRegister()};card(r,"REPORTS","DAILY PDF REPORT","Open register to select employee and date"){showRegister()}}
 private fun showRegister(){screen="register";val r=base("Daily Register");r.addView(tv("STAFF MEMBER",12,true,muted));if(staff.isEmpty()){r.addView(tv("No staff added yet",18,true,dark));r.addView(btn("+ ADD STAFF"){showStaff()});noteEdit=null;return};if(selectedStaff !in staff)selectedStaff=staff.first();val sp=Spinner(this);sp.backgroundTintList=android.content.res.ColorStateList.valueOf(green);val ad=object:ArrayAdapter<String>(this,android.R.layout.simple_spinner_item,staff){override fun getView(p:Int,v:View?,parent:ViewGroup)=super.getView(p,v,parent).apply{(this as TextView).setTextColor(dark);textSize=18f;setPadding(dp(12),dp(12),dp(12),dp(12))};override fun getDropDownView(p:Int,v:View?,parent:ViewGroup)=super.getDropDownView(p,v,parent).apply{(this as TextView).setTextColor(dark);setBackgroundColor(Color.WHITE);textSize=18f;setPadding(dp(16),dp(16),dp(16),dp(16))}};ad.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);sp.adapter=ad;sp.setSelection(staff.indexOf(selectedStaff));r.addView(sp,LinearLayout.LayoutParams(-1,dp(58)));val cal=CalendarView(this);cal.date=(SimpleDateFormat("yyyy-MM-dd",Locale.US).parse(selectedDate)?:Date()).time;r.addView(cal);val dl=tv(pretty(selectedDate),19,true,dark);dl.setPadding(0,dp(12),0,dp(8));r.addView(dl);r.addView(tv("DAILY NOTES",12,true,muted));val ed=EditText(this);noteEdit=ed;ed.hint="No notes saved for this date. Write notes here...";ed.setTextColor(dark);ed.setHintTextColor(Color.rgb(130,140,136));ed.setBackgroundColor(Color.WHITE);ed.gravity=Gravity.TOP;ed.setPadding(dp(14),dp(14),dp(14),dp(14));ed.minLines=6;r.addView(ed,LinearLayout.LayoutParams(-1,-2));loadCurrent();r.addView(btn("SAVE NOTE"){saveCurrent()});r.addView(btn("EXPORT DAILY PDF"){if(dirty())unsaved{exportPdf()}else exportPdf()});sp.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{var first=true;override fun onNothingSelected(p:AdapterView<*>?){};override fun onItemSelected(p:AdapterView<*>?,v:View?,pos:Int,id:Long){if(first){first=false;return};val next=staff[pos];guard{selectedStaff=next;showRegister()}}};cal.setOnDateChangeListener{_,y,m,d->val next=String.format(Locale.US,"%04d-%02d-%02d",y,m+1,d);if(next!=selectedDate)guard{selectedDate=next;showRegister()}}}
 private fun showStaff(){screen="staff";noteEdit=null;val r=base("Staff Members");if(staff.isEmpty()){r.addView(tv("No staff members yet.",19,true,dark));r.addView(tv("Add your first employee to start recording daily notes.",15,false,muted))};staff.toList().forEach{name->val box=LinearLayout(this);box.orientation=LinearLayout.VERTICAL;box.setPadding(dp(14),dp(12),dp(14),dp(12));box.setBackgroundColor(Color.WHITE);box.addView(tv(name,18,true,dark));val actions=LinearLayout(this);actions.orientation=LinearLayout.HORIZONTAL;actions.addView(btn("EDIT"){staffDialog(name)},LinearLayout.LayoutParams(0,-2,1f));actions.addView(btn("DELETE"){deleteStaff(name)},LinearLayout.LayoutParams(0,-2,1f));box.addView(actions);r.addView(box,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,0,0,dp(10))})};r.addView(btn("+ ADD STAFF"){staffDialog(null)})}
 private fun staffDialog(old:String?){val input=EditText(this);input.setText(old?:"");input.hint="Staff member name";input.setTextColor(dark);input.setHintTextColor(Color.rgb(95,105,101));input.setBackgroundColor(Color.WHITE);input.setPadding(dp(16),dp(12),dp(16),dp(12));val dialog=AlertDialog.Builder(this).setTitle(if(old==null)"ADD STAFF MEMBER" else "EDIT STAFF MEMBER").setView(input).setNegativeButton("CANCEL",null).setPositiveButton("SAVE"){_,_->val n=input.text.toString().trim();when{n.isBlank()->msg("Enter a staff name");staff.any{it.equals(n,true)&&!it.equals(old,true)}->msg("Staff member already exists");old==null->{staff.add(n);saveStaff();selectedStaff=n;showStaff()};else->{migrate(old,n);val i=staff.indexOf(old);if(i>=0)staff[i]=n;if(selectedStaff==old)selectedStaff=n;saveStaff();showStaff()}}}.create();dialog.setOnShowListener{dialog.getButton(AlertDialog.BUTTON_POSITIVE).setTextColor(green);dialog.getButton(AlertDialog.BUTTON_NEGATIVE).setTextColor(green);dialog.getButton(AlertDialog.BUTTON_POSITIVE).setTypeface(null,Typeface.BOLD);input.setTextColor(dark)};dialog.show()}
 private fun deleteStaff(name:String){AlertDialog.Builder(this).setTitle("DELETE "+name.uppercase()+"?").setMessage("This will permanently delete this staff member and all saved daily records associated with them.").setNegativeButton("CANCEL",null).setPositiveButton("DELETE"){_,_->val e=prefs.edit();prefs.all.keys.filter{it.startsWith("note|"+name+"|")}.forEach{e.remove(it)};e.apply();staff.remove(name);if(selectedStaff==name)selectedStaff=staff.firstOrNull();saveStaff();showStaff()}.show()}
 private fun dirty()=screen=="register"&&noteEdit!=null&&noteEdit!!.text.toString()!=originalNote
 private fun guard(action:()->Unit){if(dirty())unsaved(action)else action()}
 private fun unsaved(action:()->Unit){AlertDialog.Builder(this).setTitle("UNSAVED CHANGES").setMessage("You have unsaved changes.").setPositiveButton("SAVE"){_,_->saveCurrent();action()}.setNeutralButton("DISCARD"){_,_->action()}.setNegativeButton("CANCEL",null).show()}
 private fun loadCurrent(){originalNote=prefs.getString(key(selectedStaff!!,selectedDate),"")?:"";noteEdit?.setText(originalNote)}
 private fun saveCurrent(){val s=selectedStaff?:return;prefs.edit().putString(key(s,selectedDate),noteEdit?.text?.toString()?:"").apply();originalNote=noteEdit?.text?.toString()?:"";msg("✓ Note saved successfully")}
 private fun exportPdf(){val name=selectedStaff?:run{msg("Select a staff member first");return};val body=noteEdit?.text?.toString()?:"";try{val doc=PdfDocument();val paint=Paint(1);var pageNo=1;var page:PdfDocument.Page?=null;var canvas:Canvas?=null;var y=0f;fun newPage(){page?.let{doc.finishPage(it)};page=doc.startPage(PdfDocument.PageInfo.Builder(595,842,pageNo++).create());canvas=page!!.canvas;y=55f;paint.typeface=Typeface.DEFAULT_BOLD;paint.textSize=19f;paint.color=Color.BLACK;canvas!!.drawText("IMPILO DRILLING",48f,y,paint);y+=28;paint.textSize=15f;canvas!!.drawText("DAILY STAFF REGISTER",48f,y,paint);y+=34};fun line(t:String,bold:Boolean=false,size:Float=11f){if(y>790)newPage();paint.typeface=if(bold)Typeface.DEFAULT_BOLD else Typeface.DEFAULT;paint.textSize=size;canvas!!.drawText(t,48f,y,paint);y+=size+7};newPage();line("Employee: "+name,true,12f);line("Date: "+pretty(selectedDate),true,12f);y+=10;line("DAILY NOTES",true,12f);y+=4;val max=82;body.split("\n").forEach{para->if(para.isBlank())line("") else{var rem=para;while(rem.isNotEmpty()){var cut=minOf(max,rem.length);if(cut<rem.length){val sp=rem.lastIndexOf(' ',cut);if(sp>0)cut=sp};line(rem.substring(0,cut));rem=rem.substring(cut).trimStart()}}};y+=15;line("Generated by Impilo Drilling Staff Register",false,9f);line("Generated: "+SimpleDateFormat("d MMMM yyyy, HH:mm",Locale.getDefault()).format(Date()),false,9f);page?.let{doc.finishPage(it)};val dir=File(cacheDir,"reports");dir.mkdirs();val safe=name.replace(Regex("[^A-Za-z0-9]+"),"_").trim('_');val f=File(dir,"Impilo_Register_"+safe+"_"+selectedDate+".pdf");f.outputStream().use{doc.writeTo(it)};doc.close();val uri=FileProvider.getUriForFile(this,"za.co.impilodrilling.register.provider",f);val intent=Intent(Intent.ACTION_SEND).apply{type="application/pdf";putExtra(Intent.EXTRA_STREAM,uri);addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)};startActivity(Intent.createChooser(intent,"Open or share daily PDF"))}catch(e:Exception){msg("Unable to create PDF. Please try again.")}}
 private fun migrate(old:String,new:String){val e=prefs.edit();prefs.all.filterKeys{it.startsWith("note|"+old+"|")}.forEach{(k,v)->e.putString(k.replaceFirst("note|"+old+"|","note|"+new+"|"),v as? String?);e.remove(k)};e.apply()}
 private fun key(n:String,d:String)="note|"+n+"|"+d;private fun today()=SimpleDateFormat("yyyy-MM-dd",Locale.US).format(Date());private fun pretty(d:String)=SimpleDateFormat("EEEE, d MMMM yyyy",Locale.getDefault()).format(SimpleDateFormat("yyyy-MM-dd",Locale.US).parse(d)?:Date())
 private fun loadStaff(){staff.clear();val a=JSONArray(prefs.getString("staff","[]"));for(i in 0 until a.length())staff.add(a.getString(i))}
 private fun saveStaff(){val a=JSONArray();staff.forEach{a.put(it)};prefs.edit().putString("staff",a.toString()).apply()}
 private fun card(r:LinearLayout,title:String,value:String,sub:String,click:()->Unit){val b=LinearLayout(this);b.orientation=LinearLayout.VERTICAL;b.setPadding(dp(18),dp(16),dp(18),dp(16));b.setBackgroundColor(Color.WHITE);b.isClickable=true;b.setOnClickListener{click()};b.addView(tv(title,12,true,green));b.addView(tv(value,25,true,dark));b.addView(tv(sub,13,false,muted));r.addView(b,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,0,0,dp(12))})}
 private fun tv(s:String,z:Int,b:Boolean,c:Int)=TextView(this).apply{text=s;textSize=z.toFloat();setTextColor(c);if(b)setTypeface(typeface,Typeface.BOLD)}
 private fun btn(s:String,click:()->Unit)=Button(this).apply{text=s;setTextColor(Color.WHITE);backgroundTintList=android.content.res.ColorStateList.valueOf(green);setOnClickListener{click()}}
 private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt();private fun msg(s:String)=Toast.makeText(this,s,Toast.LENGTH_SHORT).show()
}